package com.iispl.enums;

public enum ChequeStatus {

	PENDING,
	ACCEPTED,
	REJECTED_DUPLICATE_CHEQUE_NUMBER,
	REJECTED_ACCOUNT_NOT_FOUND,
	REJECTED_CHEQUE_AMOUNT_INVALID,
	REJECTED_INSUFFICIENT_FUNDS,
	REJECTED_ACCOUNT_INACTIVE,
	REJECTED_INVALID_CHEQUE_NUMBER,
	REJECTED_INVALID_ACCOUNT_NUMBER
	
	
}
